---

- name: copy modules into place
  shell: cp -r -n "{{ item.src }}" "{{ item.dest }}"
  args:
    warn: False
  loop:
    - {src: /usr/local/src/drachtio-freeswitch-modules/modules/mod_google_transcribe/, dest: "{{freeswitch_sources_path}}/src/mod/applications/"}
    - {src: /usr/local/src/drachtio-freeswitch-modules/modules/mod_google_tts/, dest: "{{freeswitch_sources_path}}/src/mod/applications/"}
    - {src: /usr/local/src/drachtio-freeswitch-modules/modules/mod_dialogflow/, dest: "{{freeswitch_sources_path}}/src/mod/applications/"}
    - {src: /usr/local/src/drachtio-freeswitch-modules/modules/mod_aws_lex/, dest: "{{freeswitch_sources_path}}/src/mod/applications/"}
    - {src: /usr/local/src/drachtio-freeswitch-modules/modules/mod_aws_transcribe/, dest: "{{freeswitch_sources_path}}/src/mod/applications/"}

- name: copy Makefile.am, configure.ac etc into place 
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest}}"
    remote_src: no
  loop:
    - {src: "configure.ac.extra", dest: "{{freeswitch_sources_path}}/configure.ac"}
    - {src: "Makefile.am.extra", dest: "{{freeswitch_sources_path}}/Makefile.am"}
    - {src: "modules.conf.in.extra", dest: "{{freeswitch_sources_path}}/build/modules.conf.in"}
    - {src: "modules.conf.vanilla.xml.extra", dest: "{{freeswitch_sources_path}}/conf/vanilla/autoload_configs/modules.conf.xml"}

- name: check out aws-sdk-cpp
  git:
    repo: https://github.com/aws/aws-sdk-cpp.git
    dest: "{{freeswitch_sources_path}}/libs/aws-sdk-cpp"
    version: "{{aws_sdk_version}}"
    depth: 50
    accept_hostkey: yes
    force: yes

- name: update submodules
  shell: git submodule update --init --recursive
  args:
    chdir: "{{freeswitch_sources_path}}/libs/aws-sdk-cpp"

- name: check out aws-c-common
  git:
    repo: https://github.com/awslabs/aws-c-common.git
    dest: "{{freeswitch_sources_path}}/libs/aws-c-common"
    version: main
    accept_hostkey: yes
    force: yes

- name: build aws-sdk-cpp (transcribestreaming and lexv2-runtime)
  shell: |
    mkdir -p build && cd build
    cmake .. -DBUILD_ONLY="lexv2-runtime;transcribestreaming" -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_CXX_FLAGS="-Wno-unused-parameter"
    make -j 4 && make install
  args:
    chdir: "{{freeswitch_sources_path}}/libs/aws-sdk-cpp"
    warn: false

- name: check out grpc
  git: 
    repo: https://github.com/grpc/grpc
    dest: /usr/local/src/grpc
    version: "{{grpc_version}}"
    depth: 50
    accept_hostkey: yes
    force: yes
            
- name: update submodules
  shell: git submodule update --init --recursive
  args:
    chdir: /usr/local/src/grpc

- name: build grpc protobuf
  shell: ./autogen.sh && ./configure && make -j 4 install 
  args:
    chdir: /usr/local/src/grpc/third_party/protobuf

- name: build grpc
  shell: export LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH && make -j 4 && make install 
  args:
    chdir: /usr/local/src/grpc

- name: check out googleapis
  git: repo=https://github.com/davehorton/googleapis
       dest={{freeswitch_sources_path}}/libs/googleapis
       version="{{googleapis_version}}"
       accept_hostkey=yes
       force=yes

- name: build googleapis
  shell: LANGUAGE=cpp make -j 4 chdir={{freeswitch_sources_path}}/libs/googleapis

